package com.kalpa.android.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.util.Log
import android.widget.Toast
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

object PdfGeneratorHelper {
    fun generatePlaceholderPdf(context: Context) {
        val pdfDocument = PdfDocument()

        // Create a page description
        val pageInfo = PdfDocument.PageInfo.Builder(300, 600, 1).create()

        // Start a page
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()
        
        paint.color = Color.BLACK
        paint.textSize = 16f
        paint.textAlign = Paint.Align.CENTER

        canvas.drawText("KALPA Business Plan (Placeholder)", 150f, 50f, paint)
        
        paint.textSize = 12f
        canvas.drawText("This is a placeholder PDF generated by KALPA.", 150f, 80f, paint)

        // Finish the page
        pdfDocument.finishPage(page)

        // Write the document content
        val directory = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
        if (directory != null && !directory.exists()) {
            directory.mkdirs()
        }
        
        val file = File(directory, "KALPA_Business_Plan_${System.currentTimeMillis()}.pdf")
        
        try {
            pdfDocument.writeTo(FileOutputStream(file))
            Toast.makeText(context, "PDF saved to: ${file.absolutePath}", Toast.LENGTH_LONG).show()
            Log.d("PdfGeneratorHelper", "PDF saved: ${file.absolutePath}")
        } catch (e: IOException) {
            e.printStackTrace()
            Toast.makeText(context, "Error generating PDF", Toast.LENGTH_SHORT).show()
            Log.e("PdfGeneratorHelper", "PDF generation failed", e)
        }

        // Close the document
        pdfDocument.close()
    }
}
