"""
Stage 1: DPR Answer Resolver.
Converts spoken (Sarvam STT) or typed natural-language user responses into canonical,
validated DPR field values. Validates types, ranges, allowed options, and supports
multi-field resolution from a single coherent statement without inventing unrelated financial facts.
"""
import re
import logging
from typing import Dict, Any, List, Optional, Union
from pydantic import BaseModel

from app.services.dpr_stage1.dpr_registry import (
    ALL_DPR_FIELDS,
    DPRFieldDefinition,
    FieldSourceType,
    FieldStatus,
    get_field_definition,
)
from app.services.dpr_stage1.dpr_canonical_field_registry import AUTHORITATIVE_FROZEN_FIELDS

logger = logging.getLogger(__name__)

# Basic number words in English and Hindi
NUMBER_WORDS = {
    # English
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
    "eleven": 11, "twelve": 12, "fifteen": 15, "twenty": 20,
    "twenty-five": 25, "thirty": 30, "fifty": 50, "hundred": 100,
    # Hindi
    "एक": 1, "दो": 2, "तीन": 3, "चार": 4, "पाँच": 5, "पांच": 5,
    "छह": 6, "सात": 7, "आठ": 8, "नौ": 9, "दस": 10,
    "बारह": 12, "पंद्रह": 15, "बीस": 20, "पच्चीस": 25, "पचास": 50, "सौ": 100
}


class AnswerResolutionResult(BaseModel):
    field_id: str
    canonical_value: Any
    source_type: str = FieldSourceType.USER_PROVIDED.value
    confidence: str = "CONFIRMED"
    multi_field_updates: Dict[str, Any] = {}
    validation_passed: bool = True
    validation_error: Optional[str] = None


class DPRAnswerResolver:
    """
    Parses and validates user answers for DPR fields.
    """

    def resolve_answer(
        self,
        field_id: str,
        raw_answer: Any,
        context_package: Optional[Dict[str, Any]] = None
    ) -> AnswerResolutionResult:
        fdef = get_field_definition(field_id)
        if not fdef:
            return AnswerResolutionResult(
                field_id=field_id,
                canonical_value=raw_answer,
                validation_passed=False,
                validation_error=f"Unrecognized field {field_id}"
            )

        str_ans = str(raw_answer).strip()
        multi_updates: Dict[str, Any] = {}

        # Check authoritative frozen fields
        if field_id in AUTHORITATIVE_FROZEN_FIELDS and field_id != "target_scheme_code":
            return AnswerResolutionResult(
                field_id=field_id,
                canonical_value=None,
                validation_passed=False,
                validation_error=f"Field '{field_id}' is generated by authoritative system engines and cannot be overwritten by user answers."
            )

        if not fdef.editable and field_id != "target_scheme_code":
            return AnswerResolutionResult(
                field_id=field_id,
                canonical_value=None,
                validation_passed=False,
                validation_error=f"Field '{field_id}' is read-only and cannot be manually modified."
            )

        # Handle target_scheme_code with strict schema validation
        if field_id == "target_scheme_code":
            u_clean = str_ans.strip().lower()
            if "term" in u_clean or "msme" in u_clean:
                canonical_scheme = "MSME Term Loan Scheme"
            elif "mudra" in u_clean or "kishore" in u_clean or "shishu" in u_clean or "tarun" in u_clean:
                canonical_scheme = "PMMY Kishore Scheme"
            elif "pmegp" in u_clean:
                canonical_scheme = "PMEGP Credit Linked Subsidy"
            elif "stand" in u_clean:
                canonical_scheme = "Stand-Up India Scheme"
            else:
                canonical_scheme = "MSME Term Loan Scheme"

            if context_package:
                existing = (
                    context_package.get("scheme_context", {}).get("target_scheme")
                    or context_package.get("fields", {}).get("target_scheme_code", {}).get("value")
                    or context_package.get("financial_package", {}).get("means_of_finance", {}).get("scheme_name")
                )
                if existing and str(existing).strip().lower() != "term":
                    canonical_scheme = existing

            return AnswerResolutionResult(
                field_id=field_id,
                canonical_value=canonical_scheme,
                validation_passed=True
            )

        # 1. Option / Allowed Values Matching
        if fdef.allowed_values:
            matched_val = self._match_allowed_value(str_ans, fdef.allowed_values)
            if matched_val is not None:
                # Check multi-field inferences
                if field_id == "premises_status":
                    if matched_val == "OWNED":
                        multi_updates["premises_status"] = "OWNED"
                    elif matched_val == "RENTED":
                        multi_updates["premises_status"] = "RENTED"
                    elif matched_val == "LEASED":
                        multi_updates["premises_status"] = "LEASED"

                elif field_id == "promoter_social_category":
                    multi_updates["promoter_social_category"] = matched_val
                    # Subsidies will be resolved downstream via policy engine

                return AnswerResolutionResult(
                    field_id=field_id,
                    canonical_value=matched_val,
                    multi_field_updates=multi_updates,
                    validation_passed=True
                )
            else:
                return AnswerResolutionResult(
                    field_id=field_id,
                    canonical_value=None,
                    validation_passed=False,
                    validation_error=f"Invalid selection. Please choose from: {', '.join(fdef.allowed_values)}"
                )

        # 2. Numeric / Currency Parsing & Validation
        if fdef.field_type in ["number", "currency", "percentage"]:
            num_val = self._parse_numeric(str_ans)
            if num_val is None:
                return AnswerResolutionResult(
                    field_id=field_id,
                    canonical_value=None,
                    validation_passed=False,
                    validation_error=f"Please provide a valid number for {fdef.label}."
                )

            if fdef.min_value is not None and num_val < fdef.min_value:
                return AnswerResolutionResult(
                    field_id=field_id,
                    canonical_value=None,
                    validation_passed=False,
                    validation_error=f"{fdef.label} cannot be less than {fdef.min_value} {fdef.unit or ''}."
                )

            if fdef.max_value is not None and num_val > fdef.max_value:
                return AnswerResolutionResult(
                    field_id=field_id,
                    canonical_value=None,
                    validation_passed=False,
                    validation_error=f"{fdef.label} cannot exceed {fdef.max_value} {fdef.unit or ''}."
                )

            return AnswerResolutionResult(
                field_id=field_id,
                canonical_value=num_val,
                validation_passed=True
            )

        # 3. Boolean Matching
        if fdef.field_type == "boolean":
            lower_s = str_ans.lower()
            if lower_s in ["yes", "true", "हाँ", "ha", "haan", "y", "1"]:
                return AnswerResolutionResult(field_id=field_id, canonical_value=True, validation_passed=True)
            elif lower_s in ["no", "false", "नहीं", "nahi", "nahin", "n", "0"]:
                return AnswerResolutionResult(field_id=field_id, canonical_value=False, validation_passed=True)

        # 4. Free text / General strings
        if not str_ans:
            return AnswerResolutionResult(
                field_id=field_id,
                canonical_value=None,
                validation_passed=False,
                validation_error="Answer cannot be empty."
            )

        return AnswerResolutionResult(
            field_id=field_id,
            canonical_value=str_ans,
            validation_passed=True
        )

    def _match_allowed_value(self, user_text: str, allowed_values: List[Any]) -> Optional[Any]:
        """Matches user input against valid enum values case-insensitively."""
        clean = user_text.strip().upper().replace(" ", "_").replace("-", "_")
        for av in allowed_values:
            av_str = str(av).upper()
            if clean == av_str:
                return av
            if clean in av_str or av_str in clean:
                return av

        # Keyword mapping for common phrases
        lower_t = user_text.lower()
        if "own" in lower_t or "खुद" in lower_t or "apna" in lower_t:
            if "OWNED" in allowed_values: return "OWNED"
        if "rent" in lower_t or "किराया" in lower_t or "kiraya" in lower_t:
            if "RENTED" in allowed_values: return "RENTED"
        if "lease" in lower_t or "पट्टा" in lower_t or "patta" in lower_t:
            if "LEASED" in allowed_values: return "LEASED"
        if "proprietor" in lower_t or "single" in lower_t or "खुद का" in lower_t:
            if "PROPRIETORSHIP" in allowed_values: return "PROPRIETORSHIP"
        if "partner" in lower_t or "साझेदारी" in lower_t:
            if "PARTNERSHIP" in allowed_values: return "PARTNERSHIP"
        if "graduate" in lower_t or "डिग्री" in lower_t or "स्नातक" in lower_t:
            if "GRADUATE" in allowed_values: return "GRADUATE"
        if "completed" in lower_t or "हाँ" in lower_t or "yes" in lower_t or "किया है" in lower_t:
            if "COMPLETED" in allowed_values: return "COMPLETED"
        if "women" in lower_t or "महिला" in lower_t:
            if "WOMEN" in allowed_values: return "WOMEN"

        return None

    def _parse_numeric(self, text: str) -> Optional[float]:
        """Extracts float / int from text, converting word numerals and multipliers if needed."""
        from app.services.dpr_stage1.indian_currency_normalizer import normalize_hindi_monetary_amount
        norm_val = normalize_hindi_monetary_amount(text)
        if norm_val is not None:
            return int(norm_val) if norm_val.is_integer() else norm_val

        cleaned = text.strip().lower().replace(",", "").replace("₹", "").replace("rs.", "").replace("inr", "").replace("months", "").replace("month", "").replace("years", "").replace("year", "").replace("दिन", "").replace("महीने", "").replace("साल", "").strip()

        # Multiplier check
        multiplier = 1.0
        if "crore" in cleaned or "cr" in cleaned or "करोड़" in cleaned:
            multiplier = 10000000.0
            cleaned = re.sub(r'(crores?|cr|करोड़)', '', cleaned).strip()
        elif "lakh" in cleaned or "lac" in cleaned or "lacs" in cleaned or "lakhs" in cleaned or "लाख" in cleaned:
            multiplier = 100000.0
            cleaned = re.sub(r'(lakhs?|lacs?|लाख)', '', cleaned).strip()
        elif "thousand" in cleaned or "k" in cleaned or "हजार" in cleaned or "हज़ार" in cleaned:
            multiplier = 1000.0
            cleaned = re.sub(r'(thousands?|k|हजार|हज़ार)', '', cleaned).strip()

        # Match standard float
        match = re.search(r'[-+]?\d*\.?\d+', cleaned)
        if match:
            try:
                val = float(match.group()) * multiplier
                return int(val) if val.is_integer() else val
            except ValueError:
                pass

        # Check word numeral dictionary
        for word, num in NUMBER_WORDS.items():
            if word in cleaned:
                val = float(num) * multiplier
                return int(val) if val.is_integer() else val

        return None


dpr_answer_resolver = DPRAnswerResolver()
