"""
Constants and weights for Stage 11 Risk Engine.
"""

RISK_WEIGHT_FINANCIAL = 0.25
RISK_WEIGHT_MARKET = 0.20
RISK_WEIGHT_OPERATIONAL = 0.15
RISK_WEIGHT_SEASONAL = 0.10
RISK_WEIGHT_SUPPLY_CHAIN = 0.10
RISK_WEIGHT_COMPETITION = 0.10
RISK_WEIGHT_INFRASTRUCTURE = 0.10

SEVERITY_THRESHOLD_CRITICAL = 0.85
SEVERITY_THRESHOLD_HIGH = 0.65
SEVERITY_THRESHOLD_MEDIUM = 0.40
