import uuid
from sqlalchemy import Column, String, Float, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database.base import TimeStampedModel


class FeasibilityResult(TimeStampedModel):
    """
    Multivariate feasibility assessment outcome generated by the ML model and rules engine.
    """
    __tablename__ = "feasibility_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    business_id = Column(UUID(as_uuid=True), ForeignKey("business_profiles.id"), unique=True, nullable=False)

    overall_feasibility_score = Column(Float, default=0.0)  # 0 to 100
    viability_status = Column(String(50), default="pending")  # highly_viable, viable_with_conditions, risky, unviable
    ml_confidence_score = Column(Float, default=0.0)

    # Sub-component scores
    market_score = Column(Float, default=0.0)
    financial_score = Column(Float, default=0.0)
    location_score = Column(Float, default=0.0)
    entrepreneur_fit_score = Column(Float, default=0.0)

    # Dynamic SWOT
    strengths = Column(JSON, default=list)
    weaknesses = Column(JSON, default=list)
    opportunities = Column(JSON, default=list)
    threats = Column(JSON, default=list)

    # Recommendations & Pivot suggestions
    advisory_notes = Column(JSON, default=list)
    pivot_recommendations = Column(JSON, default=list)

    # Relationship
    business = relationship("BusinessProfile", back_populates="feasibility_result")
