import uuid
from sqlalchemy import Column, String, Float, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database.base import TimeStampedModel


class FeasibilityResult(TimeStampedModel):
    """
    Multivariate feasibility assessment outcome generated by the deterministic synthesis engine
    and ML prediction model slot.
    """
    __tablename__ = "feasibility_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    business_id = Column(UUID(as_uuid=True), ForeignKey("business_profiles.id"), unique=True, nullable=True)

    overall_feasibility_score = Column(Float, default=0.0)  # 0 to 100
    viability_status = Column(String(50), default="pending")  # VIABLE, VIABLE_WITH_CAUTION, CONDITIONALLY_VIABLE, NOT_FEASIBLE, DATA_INSUFFICIENT
    recommendation = Column(String(50), default="CONDITIONAL")  # YES, CONDITIONAL, NO
    confidence_score = Column(Float, default=0.0)

    # 4 Core Pillar Scores
    market_score = Column(Float, default=0.0)
    financial_score = Column(Float, default=0.0)
    entrepreneur_fit_score = Column(Float, default=0.0)
    risk_resilience_score = Column(Float, default=0.0)

    # Detailed Structured JSON Payloads
    feature_vector = Column(JSON, default=dict)
    pillar_scores = Column(JSON, default=dict)
    critical_gates = Column(JSON, default=list)
    positive_drivers = Column(JSON, default=list)
    key_constraints = Column(JSON, default=list)
    conditions = Column(JSON, default=list)

    # Dynamic SWOT
    strengths = Column(JSON, default=list)
    weaknesses = Column(JSON, default=list)
    opportunities = Column(JSON, default=list)
    threats = Column(JSON, default=list)

    # Recommendations & Pivot suggestions
    advisory_notes = Column(JSON, default=list)
    pivot_recommendations = Column(JSON, default=list)
    calculation_provenance = Column(JSON, default=list)

    # ML prediction metadata
    ml_prediction = Column(JSON, default=dict)

    # Relationship
    business = relationship("BusinessProfile", back_populates="feasibility_result")
