"""
SQLAlchemy Model for Stage 13: Dynamic SWOT Agent Persistence.
Stores structured SWOT matrix, strategic summary, recommendations, immediate actions,
evidence provenance references, and LLM telemetry.
"""
import uuid
from sqlalchemy import Column, String, Float, ForeignKey, JSON, Boolean, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database.base import TimeStampedModel


class SwotResult(TimeStampedModel):
    """
    Persisted strategic SWOT analysis outcome generated by Stage 13 Dynamic SWOT Agent.
    """
    __tablename__ = "swot_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    business_id = Column(UUID(as_uuid=True), ForeignKey("business_profiles.id"), unique=True, nullable=True)

    status = Column(String(50), default="COMPLETED", index=True)  # COMPLETED, FAILED, BLOCKED_NOT_FEASIBLE
    confidence_score = Column(Float, default=0.0)

    # Core Structured Payloads
    swot_json = Column(JSON, default=dict)  # strengths, weaknesses, opportunities, threats
    strategic_summary_json = Column(JSON, default=dict)
    recommendations_json = Column(JSON, default=list)
    immediate_actions_json = Column(JSON, default=list)
    evidence_summary_json = Column(JSON, default=dict)
    model_metadata_json = Column(JSON, default=dict)

    # Error payload (if failed)
    error_json = Column(JSON, nullable=True)

    # Relationships
    business = relationship("BusinessProfile", back_populates="swot_result", foreign_keys=[business_id])
