"""
Reason codes for M4 Banking Appraisal & Viability Engine.
Stable, machine-readable reason codes used across appraisal, risk, and validation layers.
"""
from enum import Enum


class ReasonCode(str, Enum):
    # Data Completeness & Missing Inputs
    MISSING_REVENUE = "MISSING_REVENUE"
    MISSING_OPEX = "MISSING_OPEX"
    MISSING_COGS = "MISSING_COGS"
    MISSING_DEBT_SERVICE = "MISSING_DEBT_SERVICE"
    MISSING_INTEREST = "MISSING_INTEREST"
    MISSING_PRINCIPAL = "MISSING_PRINCIPAL"
    MISSING_EQUITY = "MISSING_EQUITY"
    MISSING_NET_WORTH = "MISSING_NET_WORTH"
    MISSING_WORKING_CAPITAL = "MISSING_WORKING_CAPITAL"
    MISSING_PROJECT_COST = "MISSING_PROJECT_COST"
    MISSING_DISCOUNT_RATE = "MISSING_DISCOUNT_RATE"
    MISSING_CASH_FLOWS = "MISSING_CASH_FLOWS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNRESOLVED_DEPENDENCY = "UNRESOLVED_DEPENDENCY"

    # Math & Denominator Conditions
    ZERO_DENOMINATOR = "ZERO_DENOMINATOR"
    NEGATIVE_DENOMINATOR = "NEGATIVE_DENOMINATOR"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    ZERO_DEBT = "ZERO_DEBT"
    NOT_APPLICABLE_ZERO_INTEREST = "NOT_APPLICABLE_ZERO_INTEREST"

    # Stage 9 Reconciliation
    STAGE9_RECONCILIATION_FAILED = "STAGE9_RECONCILIATION_FAILED"
    STAGE9_RECONCILIATION_PASSED = "STAGE9_RECONCILIATION_PASSED"
    STAGE9_DSCR_MISMATCH = "STAGE9_DSCR_MISMATCH"
    STAGE9_INTEREST_MISMATCH = "STAGE9_INTEREST_MISMATCH"
    STAGE9_PRINCIPAL_MISMATCH = "STAGE9_PRINCIPAL_MISMATCH"
    STAGE9_BREAK_EVEN_MISMATCH = "STAGE9_BREAK_EVEN_MISMATCH"

    # Financial Capacity & Risk Triggers
    INSUFFICIENT_CASH_FLOW = "INSUFFICIENT_CASH_FLOW"
    WEAK_REPAYMENT_CAPACITY = "WEAK_REPAYMENT_CAPACITY"
    LOW_DSCR = "LOW_DSCR"
    LOW_INTEREST_COVERAGE = "LOW_INTEREST_COVERAGE"
    HIGH_LEVERAGE = "HIGH_LEVERAGE"
    NEGATIVE_PROFITABILITY = "NEGATIVE_PROFITABILITY"
    WEAK_LIQUIDITY = "WEAK_LIQUIDITY"
    INSUFFICIENT_WORKING_CAPITAL = "INSUFFICIENT_WORKING_CAPITAL"
    HIGH_BREAK_EVEN = "HIGH_BREAK_EVEN"
    BREAK_EVEN_CONCENTRATION = "BREAK_EVEN_CONCENTRATION"

    # Financing & Capital Structure
    FINANCING_GAP = "FINANCING_GAP"
    FINANCING_SURPLUS = "FINANCING_SURPLUS"
    PROMOTER_CONTRIBUTION_GAP = "PROMOTER_CONTRIBUTION_GAP"
    PROMOTER_CONTRIBUTION_ADEQUATE = "PROMOTER_CONTRIBUTION_ADEQUATE"

    # Validation
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_UNRESOLVED = "VALIDATION_UNRESOLVED"
