"""
Reason codes for M5 Stress Testing, Scheme Routing & Financing Optimizer.
Machine-readable enum codes providing transparent auditable rationales across
scenario stress testing, scheme eligibility, financing feasibility, and policy optimization.
"""
from enum import Enum


class M5ReasonCode(str, Enum):
    # Completeness & Unknowns
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNRESOLVED_DRIVER = "UNRESOLVED_DRIVER"
    BASELINE_UNRESOLVED = "BASELINE_UNRESOLVED"
    UNRESOLVED_WC_BASELINE = "UNRESOLVED_WC_BASELINE"
    MISSING_FINANCING_TERMS = "MISSING_FINANCING_TERMS"
    NOT_APPLICABLE = "NOT_APPLICABLE"

    # Scenario Sources & Classifications
    BASE_CASE = "BASE_CASE"
    POLICY_SCENARIO = "POLICY_SCENARIO"
    USER_SCENARIO = "USER_SCENARIO"

    # Stress & Financial Resilience
    RESILIENT = "RESILIENT"
    STRESSED = "STRESSED"
    CRITICAL = "CRITICAL"
    NOT_ASSESSABLE = "NOT_ASSESSABLE"
    DSCR_BELOW_THRESHOLD = "DSCR_BELOW_THRESHOLD"
    DSCR_UNRESOLVED = "DSCR_UNRESOLVED"
    NEGATIVE_CASH_FLOW = "NEGATIVE_CASH_FLOW"
    LIQUIDITY_STRESS = "LIQUIDITY_STRESS"
    BREAK_EVEN_EXCEEDED = "BREAK_EVEN_EXCEEDED"
    REPAYMENT_DEFICIT = "REPAYMENT_DEFICIT"
    HIGH_LEVERAGE = "HIGH_LEVERAGE"

    # Scheme Routing & Eligibility
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    INELIGIBLE_PROJECT_COST = "INELIGIBLE_PROJECT_COST"
    INELIGIBLE_LOAN_CEILING = "INELIGIBLE_LOAN_CEILING"
    VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED"
    SCHEME_LIMIT_EXCEEDED = "SCHEME_LIMIT_EXCEEDED"

    # Financing Structure & Margin Compliance
    FINANCING_GAP = "FINANCING_GAP"
    FINANCING_SURPLUS = "FINANCING_SURPLUS"
    FINANCING_BALANCED = "FINANCING_BALANCED"
    PROMOTER_CONTRIBUTION_GAP = "PROMOTER_CONTRIBUTION_GAP"
    PROMOTER_CONTRIBUTION_ADEQUATE = "PROMOTER_CONTRIBUTION_ADEQUATE"
    EXPLICIT_ZERO_PROMOTER = "EXPLICIT_ZERO_PROMOTER"
    EXPLICIT_ZERO_DEBT = "EXPLICIT_ZERO_DEBT"

    # Optimizer Selection Rationales
    FINANCING_GAP_ELIMINATED = "FINANCING_GAP_ELIMINATED"
    MARGIN_REQUIREMENT_MET = "MARGIN_REQUIREMENT_MET"
    DEBT_SERVICE_FEASIBLE = "DEBT_SERVICE_FEASIBLE"
    DOWNSIDE_RESILIENT = "DOWNSIDE_RESILIENT"
    LOWER_DEBT_SERVICE = "LOWER_DEBT_SERVICE"
    LOWER_TOTAL_INTEREST = "LOWER_TOTAL_INTEREST"
    NO_FEASIBLE_FINANCING_STRUCTURE = "NO_FEASIBLE_FINANCING_STRUCTURE"

    # Validation
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_UNRESOLVED = "VALIDATION_UNRESOLVED"
